CREATE TABLE MINISTERIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    NUM_FUNCIONARIOS INT NOT NULL,
    VERBA DOUBLE NOT NULL
);

CREATE TABLE SECRETARIA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    NUM_FUNCIONARIOS INT NOT NULL,
    VERBA DOUBLE NOT NULL,
    MINISTERIO_ID INT,
    FOREIGN KEY (MINISTERIO_ID) REFERENCES MINISTERIO(ID)
);

CREATE TABLE PRESIDENTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    PARTIDO VARCHAR(255) NOT NULL,
    DATA_ENTRADA DATE NOT NULL,
    DATA_SAIDA DATE,
    VERBA DOUBLE NOT NULL,
    SALARIO DOUBLE NOT NULL
);

CREATE TABLE MINISTRO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    PARTIDO VARCHAR(255) NOT NULL,
    DATA_ENTRADA DATE NOT NULL,
    DATA_SAIDA DATE,
    SALARIO DOUBLE NOT NULL,
    MINISTERIO_ID INT NOT NULL,
    FOREIGN KEY (MINISTERIO_ID) REFERENCES MINISTERIO(ID)
);